export type DemoSearch = {
  query: string;
  aliases: string[];
  type: 'ticker' | 'term' | 'question';
  size: 'small' | 'medium' | 'large';
  answer: string;
};

export const demoSearches: DemoSearch[] = [
  // Top 10 Tickers (as of today, for demo)
  {
    query: "AAPL",
    aliases: ["appl", "apple", "aaple", "aple"],
    type: "ticker",
    size: "small",
    answer: "Apple Inc. (AAPL) is trading at $175.23 (+1.2%)",
  },
  {
    query: "MSFT",
    aliases: ["msft", "microsoft", "microsft", "msf"],
    type: "ticker",
    size: "small",
    answer: "Microsoft Corp. (MSFT) is trading at $320.15 (+0.8%)",
  },
  {
    query: "GOOGL",
    aliases: ["googl", "google", "gogl", "gooogle"],
    type: "ticker",
    size: "small",
    answer: "Alphabet Inc. (GOOGL) is trading at $2,850.50 (+1.5%)",
  },
  {
    query: "AMZN",
    aliases: ["amzn", "amazon", "amazan", "amzon"],
    type: "ticker",
    size: "small",
    answer: "Amazon.com Inc. (AMZN) is trading at $3,350.00 (+2.1%)",
  },
  {
    query: "NVDA",
    aliases: ["nvda", "nvidia", "nvida", "nvidea"],
    type: "ticker",
    size: "small",
    answer: "NVIDIA Corp. (NVDA) is trading at $700.10 (+3.0%)",
  },
  {
    query: "TSLA",
    aliases: ["tsla", "tesla", "teslsa", "tsal"],
    type: "ticker",
    size: "small",
    answer: "Tesla Inc. (TSLA) is trading at $900.00 (+1.7%)",
  },
  {
    query: "META",
    aliases: ["meta", "facebook", "metaa", "fb"],
    type: "ticker",
    size: "small",
    answer: "Meta Platforms Inc. (META) is trading at $350.00 (+0.9%)",
  },
  {
    query: "BRK.B",
    aliases: ["brk.b", "berkshire", "berkshire hathaway", "brkb"],
    type: "ticker",
    size: "small",
    answer: "Berkshire Hathaway Inc. (BRK.B) is trading at $290.00 (+0.5%)",
  },
  {
    query: "JPM",
    aliases: ["jpm", "jpmorgan", "jp morgan", "jpmorgan chase"],
    type: "ticker",
    size: "small",
    answer: "JPMorgan Chase & Co. (JPM) is trading at $160.00 (+0.6%)",
  },
  {
    query: "V",
    aliases: ["v", "visa", "visaa", "vsa"],
    type: "ticker",
    size: "small",
    answer: "Visa Inc. (V) is trading at $230.00 (+0.4%)",
  },

  // 10 Common Financial Terms
  {
    query: "EBITDA",
    aliases: ["ebitda", "ebtda", "ebita", "ebitd", "ebit da"],
    type: "term",
    size: "medium",
    answer: "EBITDA stands for Earnings Before Interest, Taxes, Depreciation, and Amortization. It is a measure of company performance...",
  },
  {
    query: "P/E Ratio",
    aliases: ["pe ratio", "p e ratio", "price earnings ratio", "p/e"],
    type: "term",
    size: "medium",
    answer: "P/E Ratio (Price-to-Earnings Ratio) is a valuation metric for measuring a company's current share price relative to its per-share earnings.",
  },
  {
    query: "Market Cap",
    aliases: ["market cap", "market capitalization", "mkt cap", "marketcap"],
    type: "term",
    size: "medium",
    answer: "Market capitalization (Market Cap) is the total value of a company's outstanding shares of stock.",
  },
  {
    query: "Dividend Yield",
    aliases: ["dividend yield", "div yield", "dividend yld", "dividend"],
    type: "term",
    size: "medium",
    answer: "Dividend yield is a financial ratio that shows how much a company pays out in dividends each year relative to its stock price.",
  },
  {
    query: "Beta",
    aliases: ["beta", "bta", "bta value", "beta value"],
    type: "term",
    size: "medium",
    answer: "Beta is a measure of a stock's volatility in relation to the overall market.",
  },
  {
    query: "ROE",
    aliases: ["roe", "return on equity", "r o e", "return equity"],
    type: "term",
    size: "medium",
    answer: "ROE (Return on Equity) measures a corporation's profitability by revealing how much profit a company generates with the money shareholders have invested.",
  },
  {
    query: "EPS",
    aliases: ["eps", "earnings per share", "e p s", "earnings/share"],
    type: "term",
    size: "medium",
    answer: "EPS (Earnings Per Share) is the portion of a company's profit allocated to each outstanding share of common stock.",
  },
  {
    query: "Revenue",
    aliases: ["revenue", "rev", "revenu", "revenues"],
    type: "term",
    size: "medium",
    answer: "Revenue is the total amount of income generated by the sale of goods or services related to the company's primary operations.",
  },
  {
    query: "Net Income",
    aliases: ["net income", "net profit", "net earnings", "netincome"],
    type: "term",
    size: "medium",
    answer: "Net income is a company's total earnings, also called net profit or net earnings.",
  },
  {
    query: "Free Cash Flow",
    aliases: ["free cash flow", "fcf", "freecashflow", "free cashflow"],
    type: "term",
    size: "medium",
    answer: "Free cash flow (FCF) is the cash a company generates after accounting for cash outflows to support operations and maintain its capital assets.",
  },

  // 10 Financial Questions
  {
    query: "What is a stock split?",
    aliases: ["stock split", "what is stock split", "explain stock split", "stocksplit"],
    type: "question",
    size: "large",
    answer: "A stock split is a corporate action in which a company divides its existing shares into multiple shares to boost the liquidity of the shares.",
  },
  {
    query: "How do dividends work?",
    aliases: ["dividends work", "how dividends work", "explain dividends", "dividend payout"],
    type: "question",
    size: "large",
    answer: "Dividends are payments made by a corporation to its shareholders, usually as a distribution of profits.",
  },
  {
    query: "How to buy stocks?",
    aliases: ["buy stocks", "how buy stocks", "how to purchase stocks", "stock buying"],
    type: "question",
    size: "large",
    answer: "To buy stocks, you need to open a brokerage account, deposit funds, and place a buy order for the desired stock.",
  },
  {
    query: "What is an ETF?",
    aliases: ["etf", "what is etf", "explain etf", "etfs"],
    type: "question",
    size: "large",
    answer: "An ETF (Exchange-Traded Fund) is a type of investment fund and exchange-traded product, traded on stock exchanges.",
  },
  {
    query: "What is a mutual fund?",
    aliases: ["mutual fund", "what is mutual fund", "explain mutual fund", "mutualfund"],
    type: "question",
    size: "large",
    answer: "A mutual fund is an investment vehicle made up of a pool of money collected from many investors to invest in securities.",
  },
  {
    query: "What is short selling?",
    aliases: ["short selling", "what is short selling", "explain short selling", "shortsell"],
    type: "question",
    size: "large",
    answer: "Short selling is the sale of a security that is not owned by the seller, or that the seller has borrowed.",
  },
  {
    query: "How are stock prices determined?",
    aliases: ["stock prices determined", "how stock prices determined", "explain stock prices", "stock price calculation"],
    type: "question",
    size: "large",
    answer: "Stock prices are determined by supply and demand in the market, influenced by company performance, news, and overall market conditions.",
  },
  {
    query: "What is an IPO?",
    aliases: ["ipo", "what is ipo", "explain ipo", "initial public offering"],
    type: "question",
    size: "large",
    answer: "An IPO (Initial Public Offering) is the process by which a private company becomes publicly traded by offering its shares to the public for the first time.",
  },
  {
    query: "What is a bond?",
    aliases: ["bond", "what is bond", "explain bond", "bonds"],
    type: "question",
    size: "large",
    answer: "A bond is a fixed income instrument that represents a loan made by an investor to a borrower (typically corporate or governmental).",
  },
  {
    query: "How to read a stock chart?",
    aliases: ["read stock chart", "how read stock chart", "explain stock chart", "stock chart reading"],
    type: "question",
    size: "large",
    answer: "To read a stock chart, understand the axes, price movements, volume, and technical indicators shown on the chart.",
  },
]; 